### PR TITLE
Johnny s0

### PR DESCRIPTION
**Pull request by JohnnyJ0622**
I've added 'Bootstrap' and 'Font-awesome' into the project.

### CODE REVIEW

**Comment by chandleryang76** [comment]
I wonder how can you commit Gemfile.lock because Gemfile.lock is in .gitignore.
I think  there is a problem of committing Gemfile without Gemfile.lock

https://travis-ci.org/SDM2016Friends/Assignment2/builds/153874054

**Comment by JohnnyJ0622** [comment]
I've removed the file.

**Comment by chandleryang76** [comment]
It's okay to merge now, but I have a question.
Is there  reason for update `puma`?

**Comment by Isabella930514** [comment]
it's ok to merge

**Comment by allenzhong** [comment]
@chandleryang76 keeping latest version is good. It could merge.

**Pull request merged**
