### PR TITLE
Sprint0

### PR DESCRIPTION
**Pull request by allenzhong**
Tasks for sprint 0.

### CODE REVIEW

**Comment by chandleryang76** [comment]
Good. We've done

**Comment by allenzhong** [comment]
Something left should be finished in next sprint
- Rspec configuration
- Cucumber configuration

**Comment by Isabella930514** [comment]
everybody worked hard.well done. Thank you guys.

**Comment by JohnnyJ0622** [comment]
That's an amazing try!

**Comment by allenzhong** [comment]
It's ok to merge.

**Comment by Isabella930514** [comment]
It's ok

**Comment by JohnnyJ0622** [comment]
It's ok

**Pull request merged**
